version: "3"
services:
  redis:
    image: redis:alpine
    expose:
      - 6379
    ports:
      - 6379:6379
    networks:
      - ratelimit-network

  ratelimit:
    image: envoyproxy/ratelimit:master
    command: /bin/ratelimit
    ports:
      - 8080:8080
      - 8081:8081
      - 6070:6070
    depends_on:
      - redis
      - statsd
    networks:
      - ratelimit-network
    volumes:
      - ./projects/config/ratelimit:/data/ratelimit/config
    environment:
      - USE_STATSD=true
      - STATSD_HOST=statsd
      - STATSD_PORT=9125
      - LOG_LEVEL=debug
      - REDIS_SOCKET_TYPE=tcp
      - REDIS_URL=redis:6379
      - RUNTIME_ROOT=/data
      - RUNTIME_SUBDIRECTORY=ratelimit
      - RUNTIME_WATCH_ROOT=false
      - CONFIG_TYPE=${CONFIG_TYPE:-FILE}
      - CONFIG_GRPC_XDS_NODE_ID=test-node-id
      - CONFIG_GRPC_XDS_SERVER_URL=ratelimit-xds-config-server:18000

  ratelimit-xds-config-server:
    image: ratelimit-xds-config-server:latest
    command: ["-nodeID", "test-node-id", "-port", "18000", "-debug", "true"]
    expose:
      - 18000
    networks:
      - ratelimit-network
    profiles:
      - xds-config

  envoy-proxy:
    image: envoyproxy/envoy:v1.29.2
    entrypoint: "/usr/local/bin/envoy"
    command:
      - "--service-node proxy"
      - "--service-cluster proxy"
      - "--config-path /etc/envoy/proxy.yaml"
      - "--concurrency 1"
      - "--mode serve"
      - "--log-level info"
    volumes:
      - ./projects/config/envoy/proxy.yaml:/etc/envoy/proxy.yaml
    networks:
      - ratelimit-network
    expose:
      - "8888"
      - "8001"
    ports:
      - "8888:8888"
      - "8001:8001"
    depends_on:
      - ratelimit
      - app

  statsd:
    image: prom/statsd-exporter:v0.18.0
    entrypoint: /bin/statsd_exporter
    command:
      - "--statsd.mapping-config=/etc/statsd-exporter/conf.yaml"
    expose:
      - 9125
      - 9102
    ports:
      - 9125:9125
      - 9102:9102 # Visit http://localhost:9102/metrics to see metrics in Prometheus format
    networks:
      - ratelimit-network
    volumes:
      - ./projects/config/statsd-exporter/conf.yaml:/etc/statsd-exporter/conf.yaml

  prometheus:
    image: prom/prometheus:v2.37.0
    volumes:
      - ./projects/config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    networks:
      - ratelimit-network
    depends_on:
      - statsd

  grafana:
    image: grafana/grafana:9.3.6
    ports:
      - "3000:3000"
    networks:
      - ratelimit-network
    volumes:
      - ./projects/config/grafana/provisioning:/etc/grafana/provisioning
      - ./projects/config/grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - prometheus

  app:
    build: projects/application
    deploy:
        replicas: 3
    environment:
      - PORT=9000
    networks:
      - ratelimit-network

networks:
  ratelimit-network:
