{
 "title": "Rate Limit - Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<center><h1>Global Rate Limit</h1></center> <br/><center>Dashboard de Demonstração</center>"
   }
  },
  {
   "title": "Total - Requisições Dentro do Limite",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "reqs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(ratelimit_service_rate_limit_within_limit[$__interval]))) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total - Requisições Excedidas",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "reqs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(ratelimit_service_rate_limit_over_limit[$__interval]))) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requisições Dentro do Limite",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(increase(ratelimit_service_rate_limit_within_limit[1m])) by (__interval) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requisições Excedidas",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum(increase(ratelimit_service_rate_limit_over_limit[1m])) by (__interval) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}