domain: rl
descriptors:
# Descomente se quiser controlar por chave de API
#  - key: "x-api-key"
#    descriptors:
#      - key: path
#        value: /
#        rate_limit:
#          unit: minute
#          requests_per_unit: 400


  - key: path
    value: /
    rate_limit:
      unit: second
      requests_per_unit: 20





