global:
  scrape_interval: 5s  # Intervalo de coleta de métricas

scrape_configs:
  - job_name: 'statsd-exporter'
    static_configs:
      - targets: ['statsd:9102']  # Pega métricas do StatsD Exporter